spring.config.import=optional:file:.env[.properties]

spring.application.name=SPX
server.port=8080
spring.main.web-application-type=servlet

# Telegram:
telegram.api-id=${TELEGRAM_API_ID}
telegram.api-hash=${TELEGRAM_API_HASH}
telegram.phone=${TELEGRAM_PHONE}
telegram.channel-telegram.id=-5005203628
telegram.session-dir=${TD_SESSION_DIR:/tdlight-session}
logging.level.it.tdlight=WARN

# IBKR (TWS Paper)
ibkr.host=127.0.0.1
ibkr.port=7497
ibkr.client-id=7
ibkr.account=DU0960320

# Trading Range Offsets
spx.trading.option-qty=${OPTION_QTY}
spx.trading.entry-min-offset=${ENTRY_MIN_OFFSET}
spx.trading.entry-max-offset=${ENTRY_MAX_OFFSET}
spx.trading.tp-offset=${TP_OFFSET}
spx.trading.sl-offset=${SL_OFFSET}
spx.trading.allow-multiple-deals=${ALLOW_MULTIPLE_DEALS}

# alpaca:
alpaca.base-url=https://paper-api.alpaca.markets/v2
alpaca.data-ws-url=wss://stream.data.alpaca.markets/v2/iex
alpaca.key=${ALPACA_KEY}
alpaca.secret=${ALPACA_SECRET}

# OpenAI
openai.apiKey=${OPENAI_API_KEY}
openai.model=gpt-4o-mini

# PostgreSQL:
spring.datasource.url=jdbc:postgresql://localhost:5432/alpaca_bot_spx
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding=UTF-8
spring.sql.init.mode=never

# JPA / Hibernate:
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
